// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _36_Paskaita_Restaurant_System_Structure1;

#nullable disable

namespace _36_Paskaita_Restaurant_System_Structure1.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20240302233134_3")]
    partial class _3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TableId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Table", b =>
                {
                    b.Property<int>("TableNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableNumber"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.HasKey("TableNumber");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Order", b =>
                {
                    b.HasOne("_36_Paskaita_Restaurant_System_Structure1.Models.Table", "Table")
                        .WithOne("CurrentOrder")
                        .HasForeignKey("_36_Paskaita_Restaurant_System_Structure1.Models.Order", "TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Product", b =>
                {
                    b.HasOne("_36_Paskaita_Restaurant_System_Structure1.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_36_Paskaita_Restaurant_System_Structure1.Models.Table", b =>
                {
                    b.Navigation("CurrentOrder")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
